allowVolumeExpansion: true
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
  name: azuredisk
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
parameters:
  storageaccounttype: StandardSSD_LRS
volumeBindingMode: Immediate
  